const wordData = {
  elementary: [
    {
      word: "art",
      hint: "The expression of creativity through various mediums",
    },
    { word: "cat", hint: "A small furry animal" },
    { word: "dog", hint: "A loyal pet" },
    { word: "sun", hint: "The star in our solar system" },
    { word: "tree", hint: "A tall plant with a trunk" },
    { word: "book", hint: "Something you read" },
    { word: "ball", hint: "A round toy used for playing games" },
    { word: "car", hint: "A vehicle with four wheels" },
    { word: "house", hint: "A place where people live" },
    { word: "bird", hint: "An animal that can fly and has feathers" },
    { word: "fish", hint: "An animal that lives in water" },
    { word: "flower", hint: "A colorful part of a plant" },
    { word: "shoe", hint: "Something you wear on your feet" },
    { word: "hat", hint: "Something you wear on your head" },
    { word: "chair", hint: "Something you sit on" },
    { word: "table", hint: "A piece of furniture with a flat top" },
    { word: "bed", hint: "A place where you sleep" },
    { word: "toy", hint: "Something children play with" },
    { word: "doll", hint: "A toy that looks like a person" },
    { word: "bike", hint: "A vehicle with two wheels that you pedal" },
    { word: "bus", hint: "A large vehicle that carries many people" },
    { word: "moon", hint: "A bright object in the night sky" },
    { word: "star", hint: "A bright point of light in the night sky" },
    { word: "cloud", hint: "A white or gray mass in the sky" },
    { word: "rain", hint: "Water that falls from the sky" },
    { word: "food", hint: "Something you eat" },
    { word: "water", hint: "A clear liquid that you drink" },
    { word: "milk", hint: "A white liquid that comes from cows" },
    { word: "apple", hint: "A round, red or green fruit" },
    { word: "banana", hint: "A long, yellow fruit" },
    { word: "orange", hint: "A round, orange fruit" },
    { word: "pencil", hint: "Something you use to write or draw" },
    { word: "paper", hint: "Something you write or draw on" },
    { word: "crayon", hint: "A colored stick used for drawing" },
    { word: "school", hint: "A place where children learn" },
    { word: "teacher", hint: "A person who helps you learn" },
    { word: "friend", hint: "A person you like" },
    { word: "music", hint: "Sounds you enjoy" },
  ],
  middle: [
    { word: "planet", hint: "A celestial body" },
    { word: "computer", hint: "An electronic device" },
    { word: "adventure", hint: "An exciting or daring experience" },
    { word: "challenge", hint: "A difficult task or problem" },
    { word: "curiosity", hint: "A strong desire to know or learn something" },
    { word: "discovery", hint: "The act of finding something new" },
    {
      word: "explore",
      hint: "To travel through an unfamiliar area to learn about it",
    },
    { word: "imagine", hint: "To form a mental image of something" },
    {
      word: "mystery",
      hint: "Something that is difficult to understand or explain",
    },
    { word: "journey", hint: "A long trip or voyage" },
    {
      word: "knowledge",
      hint: "Facts, information, and skills acquired through experience or education",
    },
    { word: "library", hint: "A place where books are kept" },
    { word: "experiment", hint: "A scientific procedure to test a hypothesis" },
    { word: "project", hint: "A planned undertaking or task" },
    { word: "teamwork", hint: "Working together to achieve a common goal" },
    { word: "communication", hint: "The process of sharing information" },
    {
      word: "responsibility",
      hint: "The state of being accountable for something",
    },
    { word: "respect", hint: "Showing consideration for others" },
    { word: "community", hint: "A group of people living in the same place" },
    { word: "culture", hint: "The customs and beliefs of a group of people" },
    { word: "history", hint: "The study of past events" },
    { word: "geography", hint: "The study of the Earth's physical features" },
    { word: "science", hint: "The study of the natural world" },
    { word: "mathematics", hint: "The study of numbers and shapes" },
    { word: "language", hint: "A system of communication" },
    { word: "literature", hint: "Written works, such as novels and poems" },
    { word: "exercise", hint: "Physical activity for health and fitness" },
    { word: "nutrition", hint: "The process of taking in and using food" },
    {
      word: "environment",
      hint: "The surroundings or conditions in which a person, animal, or plant lives",
    },
    {
      word: "technology",
      hint: "The application of scientific knowledge for practical purposes",
    },
    { word: "innovation", hint: "A new method, idea, or product" },
  ],
  high: [
    { word: "university", hint: "Higher education institution" },
    { word: "technology", hint: "Application of scientific knowledge" },
    { word: "environment", hint: "Surroundings or conditions" },
    { word: "democracy", hint: "Government by the people" },
    { word: "psychology", hint: "Study of the mind" },
    {
      word: "ambiguous",
      hint: "Open to more than one interpretation; having a double meaning",
    },
    {
      word: "autonomous",
      hint: "Having the freedom to govern itself; self-governing",
    },
    { word: "benevolent", hint: "Well-meaning and kindly; charitable" },
    {
      word: "cognitive",
      hint: "Relating to conscious mental activities; thinking",
    },
    { word: "consensus", hint: "General agreement; collective opinion" },
    {
      word: "critique",
      hint: "A detailed analysis and assessment of something",
    },
    {
      word: "deductive",
      hint: "Reasoning from general principles to specific conclusions",
    },
    {
      word: "dichotomy",
      hint: "A division or contrast between two things that are represented as being opposed or entirely different",
    },
    {
      word: "empirical",
      hint: "Based on observation or experience rather than theory",
    },
    { word: "ephemeral", hint: "Lasting for a very short time; fleeting" },
    { word: "equilibrium", hint: "A state of balance or stability" },
    {
      word: "hypothesis",
      hint: "A proposed explanation made on the basis of limited evidence as a starting point for further investigation",
    },
    {
      word: "ideology",
      hint: "A system of ideas and ideals, especially one that forms the basis of economic or political theory and policy",
    },
    { word: "immutable", hint: "Unchanging over time or unable to be changed" },
    {
      word: "inference",
      hint: "A conclusion reached on the basis of evidence and reasoning",
    },
    {
      word: "integrity",
      hint: "The quality of being honest and having strong moral principles",
    },
    {
      word: "introspection",
      hint: "The examination or observation of one's own mental and emotional processes",
    },
    {
      word: "metaphor",
      hint: "A figure of speech in which a word or phrase is applied to an object or action to which it is not literally applicable",
    },
    {
      word: "nuance",
      hint: "A subtle difference in or shade of meaning, expression, or sound",
    },
    {
      word: "paradigm",
      hint: "A typical example or pattern of something; a model",
    },
    {
      word: "phenomenon",
      hint: "A fact or situation that is observed to exist or happen, especially one whose cause or explanation is in question",
    },
    {
      word: "pragmatic",
      hint: "Dealing with things sensibly and realistically in a way that is based on practical considerations",
    },
    {
      word: "qualitative",
      hint: "Relating to, measuring, or measured by the quality of something rather than its quantity",
    },
    {
      word: "quantitative",
      hint: "Relating to, measuring, or measured by the quantity of something rather than its quality",
    },
    {
      word: "rhetoric",
      hint: "The art of effective or persuasive speaking or writing",
    },
    {
      word: "subjective",
      hint: "Based on or influenced by personal feelings, tastes, or opinions",
    },
    {
      word: "synthesis",
      hint: "The combination of ideas to form a theory or system",
    },
    { word: "ubiquitous", hint: "Present, appearing, or found everywhere" },
    {
      word: "validate",
      hint: "Check or prove the validity or accuracy of something",
    },
    { word: "veracity", hint: "Conformity to facts; accuracy" },
  ],
  general: [
    { word: "programming", hint: "Creating computer code" },
    { word: "algorithm", hint: "Step-by-step procedure" },
    { word: "innovation", hint: "New idea or method" },
    { word: "communication", hint: "Sharing information" },
    { word: "strategy", hint: "Plan of action" },
    { word: "apple", hint: "A fruit that keeps the doctor away." },
    { word: "banana", hint: "A yellow fruit loved by monkeys." },
    { word: "orange", hint: "A citrus fruit and a color." },
    { word: "grape", hint: "Small purple or green fruits used to make wine." },
    { word: "lemon", hint: "A sour yellow citrus fruit." },
    { word: "strawberry", hint: "A red, sweet, and juicy berry." },
    { word: "blueberry", hint: "A small, round, blue-colored berry." },
    { word: "raspberry", hint: "A red or black berry with a delicate flavor." },
    { word: "watermelon", hint: "A large, green fruit with red, juicy flesh." },
    { word: "pineapple", hint: "A tropical fruit with a tough, spiky skin." },
    { word: "mango", hint: "A sweet, tropical fruit with a large seed." },
    {
      word: "kiwi",
      hint: "A small, brown fruit with green flesh and tiny black seeds.",
    },
    { word: "peach", hint: "A soft, fuzzy fruit with a large pit." },
    {
      word: "pear",
      hint: "A bell-shaped fruit that is often green or yellow.",
    },
    { word: "cherry", hint: "A small, round, red fruit with a pit." },
    { word: "apricot", hint: "A small, orange fruit similar to a peach." },
    {
      word: "plum",
      hint: "A sweet, juicy fruit that can be purple, red, or yellow.",
    },
    { word: "avocado", hint: "A creamy, green fruit often used in guacamole." },
    {
      word: "pomegranate",
      hint: "A fruit with many small, juicy seeds inside.",
    },
    { word: "lime", hint: "A small, green citrus fruit, similar to a lemon." },
    {
      word: "coconut",
      hint: "A large, hard-shelled fruit with white flesh and liquid inside.",
    },
    { word: "fig", hint: "A soft, sweet fruit with many small seeds." },
    { word: "melon", hint: "A large, sweet fruit with a smooth rind." },
    {
      word: "papaya",
      hint: "A tropical fruit with orange flesh and black seeds.",
    },
    { word: "guava", hint: "A tropical fruit with a sweet, fragrant flesh." },
    { word: "cranberry", hint: "A small, tart, red berry." },
    { word: "blackberry", hint: "A dark, sweet berry with many small seeds." },
    {
      word: "cantaloupe",
      hint: "A type of melon with orange flesh and a netted rind.",
    },
    {
      word: "honeydew",
      hint: "A type of melon with pale green flesh and a smooth rind.",
    },
    {
      word: "tangerine",
      hint: "A small, sweet citrus fruit, similar to an orange.",
    },
    {
      word: "grapefruit",
      hint: "A large, citrus fruit with a tart, juicy flesh.",
    },
    { word: "nectarine", hint: "A smooth-skinned fruit similar to a peach." },
    {
      word: "persimmon",
      hint: "A sweet, orange fruit that can be eaten fresh or dried.",
    },
    { word: "quince", hint: "A hard, yellow fruit that is often cooked." },
    { word: "date", hint: "A sweet, chewy fruit that grows on palm trees." },
    {
      word: "elderberry",
      hint: "A small, dark berry often used in jams and wines.",
    },
    { word: "gooseberry", hint: "A tart, green berry often used in pies." },
    { word: "mulberry", hint: "A sweet, dark berry that grows on trees." },
    {
      word: "passionfruit",
      hint: "A tropical fruit with a juicy, seedy interior.",
    },
    {
      word: "dragonfruit",
      hint: "A tropical fruit with bright pink skin and white or red flesh.",
    },
    {
      word: "starfruit",
      hint: "A yellow fruit with a star shape when sliced.",
    },
    { word: "limequat", hint: "A cross between a lime and a kumquat." },
    {
      word: "kumquat",
      hint: "A small, orange citrus fruit with an edible peel.",
    },
    { word: "lychee", hint: "A small, sweet fruit with a rough, red shell." },
    { word: "rambutan", hint: "A tropical fruit with a hairy red shell." },
    { word: "durian", hint: "A large, spiky fruit with a strong odor." },
    {
      word: "breadfruit",
      hint: "A large, starchy fruit that is often cooked.",
    },
    {
      word: "plantain",
      hint: "A starchy fruit similar to a banana, often cooked.",
    },
    {
      word: "jackfruit",
      hint: "A large, tropical fruit with a sweet, yellow flesh.",
    },
    { word: "guinep", hint: "A small, green fruit with a sweet, juicy flesh." },
    { word: "carambola", hint: "Another name for starfruit." },
    { word: "yuzu", hint: "A Japanese citrus fruit with a tart flavor." },
    { word: "ugli", hint: "A hybrid citrus fruit with a wrinkled skin." },
    { word: "pomelo", hint: "A large, citrus fruit with a thick rind." },
    {
      word: "mandarin",
      hint: "A small, sweet citrus fruit, similar to a tangerine.",
    },
    { word: "clementine", hint: "A small, seedless citrus fruit." },
    { word: "bloodorange", hint: "A citrus fruit with dark red flesh." },
    {
      word: "tangelo",
      hint: "A hybrid citrus fruit, a cross between a tangerine and a pomelo.",
    },
    {
      word: "boysenberry",
      hint: "A cross between a raspberry, blackberry, and loganberry.",
    },
    {
      word: "loganberry",
      hint: "A cross between a raspberry and a blackberry.",
    },
    {
      word: "cloudberry",
      hint: "A golden-colored berry that grows in cold climates.",
    },
    {
      word: "salmonberry",
      hint: "A berry that can be red, orange, or yellow.",
    },
    { word: "lingonberry", hint: "A small, red berry that is tart and sweet." },
    {
      word: "currant",
      hint: "A small, round berry that can be red, black, or white.",
    },
    { word: "juniperberry", hint: "A berry used to flavor gin." },
    { word: "acai", hint: "A dark purple berry from South America." },
    { word: "acerola", hint: "A cherry-like fruit that is high in vitamin C." },
    {
      word: "feijoa",
      hint: "A green, egg-shaped fruit with a sweet, aromatic flavor.",
    },
    {
      word: "miracleberry",
      hint: "A berry that makes sour foods taste sweet.",
    },
    { word: "goji", hint: "A small, red berry that is high in antioxidants." },
    { word: "wolfberry", hint: "Another name for goji berry." },
    {
      word: "huckleberry",
      hint: "A small, dark berry that grows in the wild.",
    },
    {
      word: "serviceberry",
      hint: "A small, sweet berry that grows on a shrub.",
    },
    {
      word: "buffaloberry",
      hint: "A small, red berry that is tart and bitter.",
    },
    {
      word: "sea buckthorn",
      hint: "An orange berry that is high in vitamins.",
    },
    {
      word: "soursop",
      hint: "A tropical fruit with a creamy, sweet-sour flesh.",
    },
    {
      word: "cherimoya",
      hint: "A tropical fruit with a sweet, custard-like flesh.",
    },
    { word: "custardapple", hint: "Another name for cherimoya." },
    { word: "sapodilla", hint: "A tropical fruit with a sweet, grainy flesh." },
    { word: "mamey", hint: "A tropical fruit with a sweet, orange-red flesh." },
    {
      word: "canistel",
      hint: "A yellow fruit with a sweet, custard-like flesh.",
    },
    {
      word: "santol",
      hint: "A tropical fruit with a sweet-sour, cottony flesh.",
    },
    {
      word: "mangosteen",
      hint: "A tropical fruit with a sweet, white, segmented flesh.",
    },
    { word: "salak", hint: "A tropical fruit with a scaly, brown skin." },
    {
      word: "longan",
      hint: "A small, round fruit with a sweet, translucent flesh.",
    },
    {
      word: "pulasan",
      hint: "A tropical fruit similar to rambutan, but with shorter spines.",
    },
    { word: "cupuacu", hint: "A tropical fruit with a creamy, tangy flesh." },
    {
      word: "jabuticaba",
      hint: "A fruit that grows directly on the trunk of the tree.",
    },
    { word: "miraclefruit", hint: "Another name for miracle berry." },
    {
      word: "cloudberry",
      hint: "A golden-colored berry that grows in cold climates.",
    },
    {
      word: "bilberry",
      hint: "A small, dark blue berry similar to a blueberry.",
    },
    { word: "dewberry", hint: "A dark, sweet berry similar to a blackberry." },
    {
      word: "elderberry",
      hint: "A small, dark berry often used in jams and wines.",
    },
    { word: "gooseberry", hint: "A tart, green berry often used in pies." },
    { word: "mulberry", hint: "A sweet, dark berry that grows on trees." },
    {
      word: "jujube",
      hint: "A small, sweet fruit that can be eaten fresh or dried.",
    },
    {
      word: "persimmon",
      hint: "A sweet, orange fruit that can be eaten fresh or dried.",
    },
    {
      word: "medlar",
      hint: "A brown fruit that is eaten when it is overripe.",
    },
    {
      word: "pawpaw",
      hint: "A tropical fruit with a sweet, custard-like flesh.",
    },
    { word: "quince", hint: "A hard, yellow fruit that is often cooked." },
    { word: "tamarind", hint: "A sour, brown fruit used in many cuisines." },
    { word: "breadnut", hint: "A starchy fruit similar to breadfruit." },
  ],
};

export default wordData;
